# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build AR Native Widgets Release

on:
    push:
        tags:
            - native-v*.*.*

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.8]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Set up Node ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm run buildReleaseNative
            - run: npm run moveReleasesNative
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: ./Native/Release/*
            - name: Clean Release folder
              run: rm -rf ./Native/Release
